  
spring:
  profiles:
    include: dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  type-aliases-package: com.vtw.domain
  
server:
  error:
    path: /error
    include-exception: true     # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: ALWAYS  # 오류 응답에 stacktrace 내용을 포함할지 여부
    whitelabel:
      enabled: false            # 브라우저 요청에 대해 서버 오류시 기본으로 노출할 페이지를 사용할지 여부

